"""empty message

Revision ID: 193bf3e6f39d
Revises: 
Create Date: 2021-04-26 23:57:07.648888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193bf3e6f39d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
